#ifndef _BDROID_BUILDCFG_H
#define _BDROID_BUILDCFG_H

#define BTM_DEF_LOCAL_NAME   "Raspberry Pi 4"

#define BTA_DM_COD {0x1A, 0x01, 0x20}

#define KERNEL_MISSING_CLOCK_BOOTTIME_ALARM TRUE

#define BTA_AV_SINK_INCLUDED           TRUE

#define MAX_PCM_FRAME_NUM_PER_TICK 28

#endif
